version: "3.4"
services:
  vpn:
    container_name: vpn
    image: bubuntux/nordvpn:latest
    cap_add:
      - net_admin # required to modify network interfaces
    restart: unless-stopped
    devices:
      - /dev/net/tun
    environment:
      - USER=${VPN_USER} # vpn user, defined in .env
      - PASS=${VPN_PASSWORD} # vpn password, defined in .env
      - COUNTRY=${VPN_COUNTRY} # vpn country, defined in .env
      - NETWORK=${NETWORK} # local network mask, defined in .env
      - PROTOCOL=UDP
      - CATEGORY=P2P
      - OPENVPN_OPTS=--pull-filter ignore "ping-restart" --ping-exit 180
      - TZ=${TZ} # timezone, defined in .env
    ports:
      - 9091:9091 # Transmission web UI
      - 51413:51413 # Transmission bittorrent daemon
      - 51413:51413/udp # Transmission bittorrent daemon
#      - 8112:8112 # port for deluge web UI to be reachable from local network
      - 9117:9117
      - 9696:9696

  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped
    network_mode: service:vpn # run on the vpn network
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/downloads:/downloads # downloads folder
      - ${CONFIG}/config/transmission:/config # config files

  prowlarr:
    image: linuxserver/prowlarr:develop-version-0.1.0.361
    container_name: prowlarr
    restart: unless-stopped
    network_mode: service:vpn # Run on the VPN Network
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG}/config/prowlarr:/config

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    network_mode: service:vpn # Run on the VPN Network
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - ${CONFIG}/config/jackett:/config # config files

  #  nzbget:
  #    container_name: nzbget
  #    image: linuxserver/nzbget:latest
  #    restart: unless-stopped
  #    network_mode: host
  #    environment:
  #      - PUID=${PUID} # default user id, defined in .env
  #      - PGID=${PGID} # default group id, defined in .env
  #      - TZ=${TZ} # timezone, defined in .env
  #    volumes:
  #      - ${ROOT}/downloads:/downloads # download folder
  #      - ${CONFIG}/config/nzbget:/config # config files

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG}/config/sonarr:/config # config files
      - ${ROOT}/tv:/tv # tv shows folder
      - ${ROOT}/downloads:/downloads # download folder
      - ${TVROOT2}/:/tv2
      - ${TVROOT3}/:/tv3
    
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG}/config/radarr:/config # config files
      - ${ROOT}/movies:/movies # movies folder
      - ${ROOT}/downloads:/downloads # download folder
      - ${MOVIEROOT2}/:/movies2
      - ${MOVIEROOT3}/:/movies3
  readarr:
    container_name: readarr
    image: hotio/readarr:pr-ed1840b
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${CONFIG}/config/readarr:/config
      - ${ROOT}/ebooks:/ebooks
      - ${ROOT}/downloads:/downloads
#    ports:
#      - 2929:8787
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    
  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${CONFIG}/config/bazarr:/config # config files
      - ${ROOT}/movies:/movies # movies folder, same as Radarr
      - ${ROOT}/tv:/tv # tv shows folder, same as Sonarr
#    ports:
#      - 61001:6767
  lazylibrarian:
    image: linuxserver/lazylibrarian
    container_name: lazylibrarian
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${CONFIG}/config/lazylib:/config
      - ${ROOT}/downloads/lazylib:/downloads
      - ${ROOT}/ebooks:/books
    ports:
      - 5299:5299
    restart: unless-stopped

  # plex-server:
  # container_name: plex-server
  #  image: linuxserver/plex:latest
  #  restart: unless-stopped
  #  network_mode: host
  #  environment:
  #    - PUID=${PUID} # default user id, defined in .env
  #    - PGID=${PGID} # default group id, defined in .env
  #    - TZ=${TZ} # timezone, defined in .env
  #    - VERSION=docker
  #  network_mode: host
  #  volumes:
  #    - ${CONFIG}/config/plex/db:/config # plex database
  #    - ${CONFIG}/config/plex/transcode:/transcode # temp transcoded files
  #    - ${ROOT}/tv:/data/tvshows # tvshows library
  #    - ${ROOT}/movies:/data/movies # tvshows library
